---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: upf-n2
spec:
  config: '{
      "cniVersion": "0.3.0",
      "name": "upf-n2",
      "type": "bridge",
      "bridge": "ens4",
      "ipam": {
        "type": "static",
        "routes": [
                { "dst": "172.23.62.0/24", "gw": "172.23.62.33" }
        ]
      }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: upf-n3
spec:
  config: '{
      "cniVersion": "0.3.0",
      "name": "upf-n3",
      "type": "bridge",
      "bridge": "ens5",
      "ipam": {
        "type": "static",
        "routes": [
                { "dst": "172.23.63.0/24", "gw": "172.23.63.33" }
        ]
      }
    }'
