---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: upf-n4
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "ipvlan",
      "master": "ens4",
      "mode": "l2",
      "ipam": {
        "type": "static",
        "routes": [
                { "dst": "172.23.64.0/28", "gw": "172.23.64.17" }
        ]
      }
    }'
