---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: upf-n3
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "ipvlan",
      "master": "ens4",
      "mode": "l2",
      "ipam": {
        "type": "static",
        "routes": [
                { "dst": "172.23.63.16/28", "gw": "172.23.63.1" }
        ]
      }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: upf-n4
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "ipvlan",
      "master": "ens5",
      "mode": "l2",
      "ipam": {
        "type": "static",
        "routes": [
                { "dst": "172.23.64.16/28", "gw": "172.23.64.1" }
        ]
      }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: upf-n6
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "ipvlan",
      "master": "ens6",
      "mode": "l2",
      "ipam": {
        "type": "static",
        "routes": [
                { "dst": "10.0.0.0/8", "gw": "172.23.66.1" }
        ]
      }
    }'
